version: '3.3'
services:

  mysql:
    image: mysql
    container_name: meu-mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=aluno
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: meu-db-admin
    restart: always
    links:
      - mysql
    ports:
      - 9001:80
    environment:
      - PMA_ARBITRARY=1
  php:
    container_name: meu-php
    build: .
    volumes:
      - ./src/php:/var/www/html
    ports:
      - 9000:80
    links:
      - mysql
